# Generated by Django 4.2.7 on 2024-01-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscribers_new',
        ),
    ]
